export enum CurrencyEnum {
  USD = "USD",
  EUR = "EUR",
  RUB = "RUB",
  JPY = "JPY",
  GBP = "GBP",
  CHF = "CHF",
  CNY = "CNY",
  BYN = "BYN",
  KZT = "KZT",
  UAH = "UAH",
  PLN = "PLN",
  AUD = "AUD",
  CAD = "CAD",
  NZD = "NZD",
  SGD = "SGD",
  SEK = "SEK",
  NOK = "NOK",
  DKK = "DKK",
  TRY = "TRY",
  INR = "INR",
  BRL = "BRL",
  ZAR = "ZAR",
  MXN = "MXN",
  ILS = "ILS",
  HKD = "HKD",
}

export const CurrencyList = Object.values(CurrencyEnum).sort();

export const CURRENCY_NAMES: Record<CurrencyEnum, string> = {
  [CurrencyEnum.USD]: "Доллар США",
  [CurrencyEnum.EUR]: "Евро",
  [CurrencyEnum.RUB]: "Российский рубль",
  [CurrencyEnum.JPY]: "Японская иена",
  [CurrencyEnum.GBP]: "Британский фунт",
  [CurrencyEnum.CHF]: "Швейцарский франк",
  [CurrencyEnum.CNY]: "Китайский юань",
  [CurrencyEnum.BYN]: "Белорусский рубль",
  [CurrencyEnum.KZT]: "Казахстанский тенге",
  [CurrencyEnum.UAH]: "Украинская гривна",
  [CurrencyEnum.PLN]: "Польский злотый",
  [CurrencyEnum.AUD]: "Австралийский доллар",
  [CurrencyEnum.CAD]: "Канадский доллар",
  [CurrencyEnum.NZD]: "Новозеландский доллар",
  [CurrencyEnum.SGD]: "Сингапурский доллар",
  [CurrencyEnum.SEK]: "Шведская крона",
  [CurrencyEnum.NOK]: "Норвежская крона",
  [CurrencyEnum.DKK]: "Датская крона",
  [CurrencyEnum.TRY]: "Турецкая лира",
  [CurrencyEnum.INR]: "Индийская рупия",
  [CurrencyEnum.BRL]: "Бразильский реал",
  [CurrencyEnum.ZAR]: "Южноафриканский рэнд",
  [CurrencyEnum.MXN]: "Мексиканское песо",
  [CurrencyEnum.ILS]: "Израильский шекель",
  [CurrencyEnum.HKD]: "Гонконгский доллар",
};